config/routes.rb
Rails.application.routes.draw do
  get 'daily_balances/show'
  # static_pages
  get "/home",  to: "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about", to: "static_pages#about"
  root "static_pages#home"
  
  # users
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i[new create edit update] do
    resources :daily_balances, only: :show, param: :record_date
    resource :images, only: %i[edit update], module: :users
    resource :image_initializations, only: :update, module: :users
    resource :self_categories, only: %i[new create], module: :users
  end

  # book_records
  resources :book_records, only: %i[create destroy]

  # ログイン機能 sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
  end


  # 試用ユーザーへログインする
  get "/sample_login", to: "sessions#sample_login"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  # 今月分の情報だけ抽出して、その合計を返す。
  def extract_balances_of_current_month(user, direction)
    current_month_records = DailyBalance.where(user_id: user.id, record_date: Time.zone.now.in_time_zone.all_month)
    sum = 0
    current_month_records.each do |record|
      sum += if direction.zero?
               record.expenditure
             else
               record.income
             end
    end

    sum
  end
end

app/views/static_pages/_book_record_form.html.erb
<div class="book-record-form-on-sidebar">
  <button class="book-record-form-title"
      data-toggle="collapse"
      data-target="#example-1"
      aria-expand="false"
      aria-controls="example-1">収支の登録(クリックで展開)</button>
  <div class="collapse" id="example-1">
    <div class="book-record-form">
      <%= form_for(:book_record, url: book_records_path) do |f| %>
        <div class="direction-radio">
          <label><%= f.radio_button :direction, 0, :checked => "checked" %> 支出</label>
          <label><%= f.radio_button :direction, 1 %> 収入</label>
        </div>

        <div class="category-select">
          <%= f.label :category, "経費種別", class: "book-record-form-control" %>
          <%= f.hidden_field :category, :value => 0 %>
          <%= f.select :category, Category.where("(user_id = ?) OR (user_id = ?)", 0, current_user.id).map { |category| [category.name, category.id] } %>
        </div>

        <div class="amount-number-field">
          <%= f.label :amount, "金額", class: "book-record-form-control" %>
          <%= f.number_field :amount, class: "book-record-form-control" %> 円
        </div>

        <div class="record-date-field">
          <%= f.label :record_date, "日付", class: "book-record-form-control" %>
          <%= f.date_select :record_date, default: Time.zone.now, class: "book-record-form-control" %>
        </div>

        <div class="comment-field">
          <%= f.label :comment, "メモ", class: "book-record-form-control" %>
          <%= f.text_area :comment, class: "book-record-form-control", size: "25x3" %>
        </div>

        <%= f.submit "収支の登録", class: "btn btn-primary book-record-submit-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/_home_logged_in.html.erb
<div class="profile_infomation">
  <div class="profile-header">
   
  </div>
  <div class="col-md-3 col-sm-12 profile-sidebar">
    <div class="profile-icon">
     
    </div>
    <div class="profile-name">
      <%= "#{current_user.name} さん" %>
    </div>
    <div class="profile-created_at">
      <%= "#{current_user.created_at.strftime('%Y年%m月%d')}日に登録" %>
    </div>
    <%= render("static_pages/book_record_form") %>
  </div>
  <div class="col-md-9 col-sm-12 profile-information">
    <%= render("shared/carousel", user: current_user) %>
  <div>
</div>

app/views/static_pages/_home_not_logged_in.html.erb
<div class="jumbotron home-jumbotron">
  <h1 class="display-4">経費管理アプリ</h1>
  <p class="lead">このアプリケーションは、会社の経費をweb上で管理するアプリケーションです。</p>
  <hr class="my-4">
  <p>まだ社員登録していない方は登録しましょう！</p>
  <a class="btn btn-lg signup-button" href="/signup" role="button">社員登録</a>
  <div class="sample-login">
    <p>すでに社員として登録されている方はこちら</p>
    <a class="btn btn-lg signup-button" href="/login" role="button">ログイン</a>
  </div>
　<div class= "logout-top">
    <p>社員の方のためのLINEによる各種連絡の登録はこちら</p>
    <a href="https://lin.ee/vpMYZbq" id="line"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="58" border="0"></a>
  </div>
</div>

app/views/static_pages/about.html.erb
<%= provide(:title, "アプリの説明") %>
<h1>このアプリケーションは・・・</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "ヘルプ") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%= provide(:title, "ホーム") %>
<% if logged_in? %>
  <%= render("static_pages/home_logged_in") %>
<% else %>
  <%= render("static_pages/home_not_logged_in") %>
<% end %>