config/routes.rb
Rails.application.routes.draw do
  get 'daily_balances/show'
  # static_pages
  get "/home",  to: "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about", to: "static_pages#about"
  root "static_pages#home"
  
  # users
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i[new create edit update] do
    resources :daily_balances, only: :show, param: :record_date
    resource :images, only: %i[edit update], module: :users
    resource :image_initializations, only: :update, module: :users
    resource :self_categories, only: %i[new create], module: :users
  end

  # book_records
  resources :book_records, only: %i[create destroy]

  # ログイン機能 sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
  end


  # 試用ユーザーへログインする
  get "/sample_login", to: "sessions#sample_login"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :book_records, dependent: :destroy
  has_many :daily_balances, dependent: :destroy
  before_save { email.downcase! }
  mount_uploader :img, ImgUploader
  mount_uploader :header_image, HeaderImageUploader
  validates(:name, presence: true, length: { maximum: 20 })
  REGEX_FOR_VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, presence: true,
                    length: { maximum: 128 },
                    uniqueness: { case_sensitive: false },
                    format: { with: REGEX_FOR_VALID_EMAIL })
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates(:password, presence: true, length: { minimum: 8 }, allow_nil: true)
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def set_remember_digest
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def login_cookie_forget
    update_attribute(:remember_digest, nil)
  end

  def sum_of_amount_for_expenditure
    sum_expenditure = 0
    book_records.each do |record|
      sum_expenditure += record.amount if record.direction == zero
    end
  end

  def sum_of_amount_for_income
    sum_income = 0
    book_records.each do |record|
      sum_income += record.amount if record.direction == 1
    end
  end
  
   # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users/image_initializations_controller.rb
class Users::ImageInitializationsController < ApplicationController
  before_action :find_user, only: :update
  before_action :logged_in_user, only: :update
  before_action :correct_user_for_child_controller, only: :update

  def update
    @user.img = "default_img.png"
    @user.header_image = "default_header_image.png"
    if @user.save
      flash[:success] = "画像を初期画像へ戻しました。"
      redirect_to(edit_user_images_path(@user))
    else
      flash.now[:danger] = "エラーが発生しました。時間をおいてもう一度実行してみてください。"
      render("users/images#edit")
    end
  end
end

app/controllers/users/images_controller.rb
class Users::ImagesController < ApplicationController
  before_action :find_user, only: %i[edit update]
  before_action :logged_in_user, only: %i[edit update]
  before_action :correct_user_for_child_controller, only: %i[edit update]

  def edit
    @settings_class = ""
    @images_class = "active"
    @category_class = ""
  end

  def update
    if @user.update_attributes(user_images_params)
      flash[:success] = "画像を更新しました。"
      redirect_to(edit_user_images_path(@user))
    else
      flash.now[:danger] = "エラーが発生しました。時間をおいてもう一度実行してみてください。"
      render("users/images#edit")
    end
  end
end

app/controllers/users/self_categories_controller.rb
class Users::SelfCategoriesController < ApplicationController
  before_action :find_user, only: %i[new create]
  before_action :logged_in_user, only: %i[new create]
  before_action :correct_user_for_child_controller, only: %i[new create]

  def new
    @category = Category.new
    @settings_class = ""
    @images_class = ""
    @category_class = "active"
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "新しい収支カテゴリを登録しました。"
      redirect_to(new_user_self_categories_url)
    else
      flash.now[:danger] = "エラーが発生しました。時間をおいてもう一度実行してみてください。"
      render("users/self_categories#new")
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :color, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]

  def show
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.img = "default_img.png"
    @user.header_image = "default_header_image.png"
    if @user.save
      log_in(@user)
      flash[:success] = "ようこそ！ #{@user.name}さん！"
      redirect_to(root_url)
    else
      render("new")
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    @settings_class = "active"
    @images_class = ""
    @category_class = ""
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "社員情報を更新しました。"
      redirect_to(edit_user_path(@user))
    else
      render("settings_edit")
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def basic_info_params
   params.require(:user).permit(:department, :basic_time, :work_time)
  end
  
  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
      redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
  end

  # beforeフィルター

  # paramsハッシュからユーザーを取得します。
  def set_user
    @user = User.find(params[:id])
  end

  # ログイン済みのユーザーか確認します。
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  # システム管理権限所有かどうか判定します。
  def admin_user
    redirect_to root_url unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, '編集') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "社員情報の変更") %>
<div class="settings-title">
  社員情報の変更
</div>
<div class="row">
  <%= render("shared/setting_sidebar", settings: @settings_class, images: @images_class, category: @category_class) %>
  <div class="col-md-6 settings-form">
    <%= form_for(@user, url: user_path(@user)) do |f| %>
      <%= render("shared/error_messages") %>

      <%= f.label :name, "社員名"%>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :department, class: "所属" %>
      <%= f.text_field :department, class: "form-control" %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "設定の変更", class: "btn settings-update-button" %>
    <% end %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, '社員一覧') %>
<h1>社員一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th class="center"><%= User.human_attribute_name :department %></th>
        <% if current_user.admin? %>
         
         
        <% end %>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td>
        <% if current_user.admin? %>
          
          
        <% end %>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, '新規社員登録') %>
<div class="signup-title">
  新規会員登録
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3 signup-form">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render("shared/error_messages") %>

      <%= f.label :name, "社員名(必須項目)"%>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, "メールアドレス(必須項目)" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :department, class: "所属" %>
      <%= f.text_field :department, class: "form-control" %>

　　　<%= f.label :password, "パスワード(必須項目)" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "パスワードの確認(必須項目)" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "社員登録", class: "btn signup-button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>
</div>
<div class="col-md-10 col-md-offset-1 user-show-table">
  <table class="table table-condensed table-bordered table-hover" id="table-users">
    
    <% if current_user.admin? %>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
    <% end %>
  　<tr>
      <th>所属</th>
      <td><%= @user.department %></td>
    </tr>
  </table>
</div>
<div class="profile_infomation">
　<div class="col-md-11 col-sm-12 profile-information">
    <%= render("shared/carousel", user: @user) %>
  <div>
</div>