config/routes.rb
Rails.application.routes.draw do
  get 'daily_balances/show'
  # static_pages
  get "/home",  to: "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about", to: "static_pages#about"
  root "static_pages#home"
  
  # users
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i[new create edit update] do
    resources :daily_balances, only: :show, param: :record_date
    resource :images, only: %i[edit update], module: :users
    resource :image_initializations, only: :update, module: :users
    resource :self_categories, only: %i[new create], module: :users
  end

  # book_records
  resources :book_records, only: %i[create destroy]

  # ログイン機能 sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
  end


  # 試用ユーザーへログインする
  get "/sample_login", to: "sessions#sample_login"
end

app/views/shared/_calendar.html.erb
<%= month_calendar(attribute: :record_date, events: user.daily_balances.all) do |date, balances| %>
  <div class="day-number">
    <%= date.day %>
  </div>
  <% balances.each do |balance| %>
    <div class="simple-calendar-date">
      <% if !empty_daily_balance?(balance) %>
        <%= link_to "", user_daily_balance_url(user, balance.record_date) %>
        <div class="amount-expenditure">
          支出: ¥<%= balance.expenditure %>
        </div>
        <div class="amount-income">
          収入: ¥<%= balance.income %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_carousel.html.erb
<div id="user_statistics_carousel" class="carousel slide" data-ride="carousel" data-interval="false" style="height:600px">
  <ol class="carousel-indicators">
    <li data-target="#user_statistics_carousel" data-slide-to="0" class="active"></li>
    <li data-target="#user_statistics_carousel" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <div class="monthly-balances-title">
        <%= "#{user.name} さんの収支カレンダー" %>
      </div>
      <%= render("shared/calendar", user: user) %>
    </div>
    
    <div class="item">
      <div class="monthly-balances-title">
        <%= "統計情報" %>
      </div>
      <%= render("shared/user_statistics", user: user) %>
    </div>
  </div>
	<a class="left carousel-control" href="#user_statistics_carousel" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Prev</span>
	</a>
	<a class="right carousel-control" href="#user_statistics_carousel" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      フォームの入力内容にエラーがあります。
    </div>
    <ul class="error-details">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_setting_sidebar.html.erb
<div class="col-md-3 settings-sidebar list-group">
  <%= link_to "基本情報の変更", edit_user_path(@user), class: "list-group-item list-group-item-action #{settings}" %>
  <%= link_to "収支カテゴリの追加", new_user_self_categories_path(@user), class: "list-group-item list-group-item-action #{category}" %>
</div>

app/views/shared/_user_statistics.html.erb
<div class="user-statistics">
  <div class="aggregation-period">
    <%= "#{Time.zone.now.year}年 #{Time.zone.now.month}月度の統計情報" %>
  </div>
  <div class="monthly-expenditure">
    月の総支出: <%= extract_balances_of_current_month(user, 0) %> 円
  </div>
  <div class="monthly-income">
    月の総収入: <%= extract_balances_of_current_month(user, 1) %> 円
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-12 exp-inc-chart">
      <div class="chart-title">
        <%= "今月の収支比" %>
      </div>
      <div class="chart">
        <%= pie_chart({ "収入" => extract_balances_of_current_month(user, 1), 
                        "支出" => extract_balances_of_current_month(user, 0)}, 
                        colors: ["#6cff5f","#ff8080"], suffix: "円", thousands: ",") %>
      </div>
    </div>
    <div class="col-md-6 col-sm-12 category-chart">
      <div class="chart-title">
        <%= "今月のカテゴリ別支出" %>
      </div>
      <div class="chart">
        <%= pie_chart(*monthly_expenditure_by_category(user, Time.zone.now)) %>
      </div>
    </div>
  </div>
</div>