config/routes.rb
Rails.application.routes.draw do
  get 'daily_balances/show'
  # static_pages
  get "/home",  to: "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about", to: "static_pages#about"
  root "static_pages#home"
  
  # users
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i[new create edit update] do
    resources :daily_balances, only: :show, param: :record_date
    resource :images, only: %i[edit update], module: :users
    resource :image_initializations, only: :update, module: :users
    resource :self_categories, only: %i[new create], module: :users
  end

  # book_records
  resources :book_records, only: %i[create destroy]

  # ログイン機能 sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
  end


  # 試用ユーザーへログインする
  get "/sample_login", to: "sessions#sample_login"
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-dark navbar-fixed-bottom footer-navbar">
  <div class="container">
    <ul class="nav navbar-dark navbar-nav navbar-right">
     
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="header-tohome">
        <a href="/">経費管理アプリ</a>
      </div>
    </div>
    
    

    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
        <% if logged_in? %>
            <li><%= link_to "社員一覧", users_path %></li>
            <li><%= link_to "設定", edit_user_path(@current_user) %></li>
            <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% else %>
          <li class="navlist"><%= link_to "ログイン", "/login", class: "header-login" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_script_for_IE9.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <%= render("layouts/script_for_IE9") %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <% if logged_in? %>
    <body class='<%= "#{controller.controller_name} body-logged-in" %>'>
  <% else %>
    <body class='<%= "#{controller.controller_name}" %>'>
  <% end %>
    <%= render("layouts/header") %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render("layouts/footer") %>
  </body>
</html>